### ISSUE TITLE
VCs for libraries are dropped if a binary is present

### ISSUE THREAD

**Issue by Armael** [creusot-rs/creusot#1178]
repro example:

Cargo.toml:
```
[package]
name = "toto"
version = "0.1.0"
edition = "2021"

[dependencies]
creusot-contracts = { path = "/home/armael/recherche/creusot/creusot-contracts" }
```

`src/main.rs`:
```rust
use creusot_contracts::*;

fn main() {
    let x = toto::foo();
    proof_assert!(x@ >= 0);
}
```

`src/lib.rs`:
```rust
use creusot_contracts::*;

#[ensures(result@ == 42)]
pub fn foo() -> i32 {
   -1
}
```

Then launching `cargo creusot why3 ide` only shows VC for `main.rs`, and verification "passes".

**Comment by xldenis** [comment]
Oh... try passing `--lib`?

**Comment by xldenis** [comment]
It may also be the case that multiple `.coma` files were generated, look inside of `target/`

**Comment by xldenis** [comment]
normally you should be able to pass it to `cargo creusot` after `--`

**Comment by Armael** [comment]
OK, indeed, `cargo creusot -- --lib` will replace the `.coma` file with the VCs for the library instead of the executable.
So in principle by juggling `cargo creusot`, `cargo creusot -- --lib` and `cargo creusot why3 ide` one can verify all the VCs of the project. This is quite cumbersome, though...

**Comment by xldenis** [comment]
> So in principle by juggling cargo creusot, cargo creusot -- --lib and cargo creusot why3 ide one can verify all the VCs of the project. This is quite cumbersome, though...

Indeed. The first step would be to figure out why the `bin` is not producing `foo-bin.coma` which it should be doing, then at least one invocation would produce both the `lib` and `bin` outputs.

**Comment by Armael** [comment]
Well, this is now solved by #1172 when using the new mode with per-module .coma files.
I'm closing this since we'll probably get rid of the "single .coma" mode at some point anyway.

**Comment by jhjourdan** [comment]
I'm reopening this issue, since the "single .coma" mode still exists, and because there still seems to be a problem somewhere.

This is too dangerous a soundness issue: the user thinks she has verified the crate, but in fact she has done nothing!

**Comment by Lysxia** [comment]
There used to be a `bin-mykrate.coma` output for executable crates before I removed it while adding the `--output-dir` option, but already then if you were building an executable and a library at the same time they were going to walk over each other because `cargo-creusot` only has room for a single file name to pass to `creusot-rustc` for both crates. Here in the diff that removed the function that constructed the `bin-mykrate.coma` filename, we can see there's a vector of targets where only the first element was used:

https://github.com/creusot-rs/creusot/pull/1172/files#diff-002fa4fa38c2cc45903c5b9374acead0875ac96a27fa5bd6b886c9678d59e39eL48

That only worked when invoking cargo on one crate at a time.

#1185 fixes this by moving the logic for picking the output file into `creusot-rustc`.
